### PR TITLE
fixed indexing in this model to reflect psql's starting by index=1 no…

### PR DESCRIPTION
**Pull request by aladams2791**
fixed indexing in this model to reflect psql's starting by index=1, not 0-indexing

rewrote psql file. Now statements and profiles should look as intended

### CODE REVIEW

**Comment by aladams2791** [comment]
@rmferrer , merge pull at your convenience 💃

**Comment by rmferrer** [comment]
hey @aladams2791, two questions:
1) is the fix to the off-by-1 error that surfaced in statement summaries a new model? if so, can you also change the latest simlink to point to this new model (otherwise we won't see this change)
2) where is the change to the psql file?

**Comment by aladams2791** [comment]
The issue was the model was trained with pt_ids started at 0, but the pt_ids in the database started at 1. Two options were fix the indexing in the model OR in the DB.

I tried resetting the index to the DB to start indexing at 0, but it was hard enough that it seemed against orthodoxy of psql, so decided to just retrain (only renamed) the exact same model but with different document labels (i.e.  pt_ids).

Because the model didn't change, only the names of the documents (to reflect index-by-1 of the pt_ids), I overwrote the august 16 model. No symlink change necessary

**Comment by rmferrer** [comment]
OK great. what about the psql file? in any case I dont think we need it since I deleted all .sql files to favor db management through rails migrations

**Comment by aladams2791** [comment]
@rmferrer yeah there's no inclusion of any .sql file (did i accidentally include?), nor should there be

**Pull request merged**
